workout/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    #記事関連
    path('article-list/',views.ArticleListView.as_view(),name="article_list"),
    path('article-detail/<int:pk>/',views.detail,name="article_detail"),
    path('article-create/',views.ArticleCreateView.as_view(),name="article_create"),
    path('article-update/<int:pk>/',views.ArticleUpdateView.as_view(),name="article_update"),
    path('article-delete/<int:pk>/',views.ArticleDeleteView.as_view(),name="article_delete"),

    #コメント関連
    path('comment-create/<int:num>/',views.CommentCreateView.as_view(),name="comment_create"),


]

workout/article/models.py
from django.db import models
from accounts.models import CustomUser
# Create your models here.
class Article(models.Model):
    """記事用モデル"""
    user = models.ForeignKey(CustomUser,on_delete=models.PROTECT,blank=True,null=True)
    photo = models.ImageField(blank=True)
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True,null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Comment(models.Model):
    """コメントモデル"""
    article = models.ForeignKey(Article,related_name='comments',on_delete=models.CASCADE,blank=True,null=True)
    comment = models.TextField(blank=True,null=True)
    created_at = models.DateField(auto_now_add=True)

workout/article/forms.py
from .models import Article, Comment
from django import forms
class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('photo','title','content')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

workout/article/views.py
from django.shortcuts import render,redirect
from .models import Article,Comment
from django.views import generic
from .forms import ArticleCreateForm,CommentCreateForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import Http404,JsonResponse
# Create your views here.
class ArticleListView(generic.ListView):
    model = Article
    template_name = 'article_list.html'
    paginate_by = 5

    def get_queryset(self):
        articles = Article.objects.all().order_by('-created_at')
        return articles

def detail(request, pk):
    try:
        article = Article.objects.get(pk=pk)
    except Article.DoesNotExist:
        raise Http404("Article does not exist")

    context = {
        'article': article,
        'comments':article.comments.order_by('-created_at')
    }
    return render(request, 'article_detail.html', context)

class ArticleCreateView(LoginRequiredMixin,generic.CreateView):
    model = Article
    template_name = 'article_create.html'
    form_class = ArticleCreateForm

    success_url = reverse_lazy('article:article_list')

    def form_valid(self,form):
        article = form.save(commit=False)
        article.user = self.request.user
        article.save()
        
        return super().form_valid(form)

    def form_invalid(self,form):
      
        return super().form_invalid(form)


class ArticleUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'article_update.html'
    def get_success_url(self):
        return reverse_lazy('article:article_detail',kwargs={'pk':self.kwargs['pk']})

    def form_valid(self,form):
        messages.success(self.request,'更新を完了しました')
        
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.error(self.request,'更新ができませんでした')
        return super().form_invalid(form)


class ArticleDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy('article:article_list')

    def delete(self,request,*args,**kwargs):
        messages.success=(self.request,"削除しました")
        return super().delete(request,*args,**kwargs)

class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentCreateForm
    template_name = 'comment_create.html'
    

    def get_success_url(self):
        return reverse_lazy('article:article_detail',kwargs={'pk':self.kwargs['num']})

   
    def form_valid(self,form):
        comment = form.save(commit=False)
        comment.article = Article.objects.get(pk=self.kwargs.get('num'))
        comment.save()
        
        return super().form_valid(form)

    def form_invalid(self,form):
        
        return super().form_invalid(form)

workout/article/templates/article_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}記事の作成{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
<p>新しい記事の投稿</p>
<p><form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
       {{ form.as_table }}
   </table>
<button type="submit" class="btn btn-primary">投稿</button>

</form></p>
</div>
</div>
</div>

{% endblock %}

workout/article/templates/article_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}投稿一覧{% endblock %}

{% block activate_article_list %}active{% endblock %}


{% block header %}
<link href="{% static 'css/ajast.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form method="POST">
            {% csrf_token %}
            <p>記事を削除してもいいですか？</p>
            <button class="btn btn-primary" type="submit">削除する</button>

            </form>
</div></div></div>
{% endblock %}

workout/article/templates/article_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title%}記事の詳細{% endblock %}

{% block contents %}

<article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

{% if article.photo %}
<p><img src="{{ article.photo.url }}" width="650px" height="350px"></p>
{% endif %}

<div>
    <h2 class="section-heading">{{ article.title }}</h2>
</div>

<div>
    {{ article.content | linebreaksbr }}

    
</div>

<div>
    <strong>作成日時</strong>
    {{ article.created_at }}

    {% if request.user == article.user %}
    <a class="btn btn-primary" href="{% url 'article:article_update' article.pk %}">編集</a>
    <a class="btn btn-primary" href="{% url 'article:article_delete' article.pk %}">削除</a>
    {% endif %}
</div>

<p><a class="btn btn-primary" href="{% url 'article:comment_create' article.pk %}">コメントする</a></p>

{% for comment in comments %}
<div class="post-preview">
    <h3 class="post-subtitle">{{ comment.comment | linebreaksbr }}</h3>
<div>{{ comment.created_at}}</div>
</div>
<hr>
{% endfor %}

</div>
</div>
</div></article>



{% endblock %}

workout/article/templates/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}投稿一覧{% endblock %}
{% block add %}   
<link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock %}


{% block activate_article_list %}active{% endblock %}


{% block header%}
<style type="text/css">
  a {color:blue;}
  </style>
{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h2>投稿をして、ダイエット記録や役立つ体験を共有しましょう！</h2>
      {% if user.is_authenticated %}
        <a href="{% url 'article:article_create' %}">投稿を作成する</a>
        
      {% else %}
       (記事を投稿するには、<a href="{% url 'account_login' %}">ログイン</a>が必要です)
       <br>
      {% endif %}

        {% for article in article_list %}
        <div class="post-preview">
         
          <a href="{% url 'article:article_detail' article.pk %}">
            <p class="post-title">
              <img src="{{ article.photo.url }}" width="150px" height="150px"><span id="title">{{ article.title }}</span>
            </p>
            <p class="post-subtitle">
              {{ article.content | truncatechars:30 }}
            </p>
          </a>
          <p class="post-meta">{{ article.created_at }}</p>
        </div>
        <hr>
  
        {% empty %}
        <p>まだ記事がありません。記事を投稿しましょう！</p>

      </div></div></div>
        {% endfor %}
    
        <!--ページネーション機能-->
        {% if is_paginated %}
        <div class="clearfix">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% endif %}
        <!--ページ数の表示-->
      {% for page_num in page_obj.paginator.page_range %}
      {% if page_obj.number == page_num %}
      <li class="page-item">
        <a class="page-link" href="#">{{ page_num }}</a>
      </li>

      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ page_num }}"></a></li>
      {% endif %}
      {% endfor %}

      <!--次のページに移行-->
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-item" href="?page={{ page_obj.next_page_number }}">
        <span aria-hidden="true">&raquo;</span>
      </a></li>
      {% endif %}
      </ul>
      </div>
      {% endif %}

    
      

{% endblock %}

workout/article/templates/article_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}編集画面{% endblock %}
{% block activate_article_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <button type="submit" class="btn btn-primary">更新</button>
        </form>
        </div>
    </div>
</div>

{% endblock %}

workout/article/templates/base.html
{% load static %}
<html lang="ja">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
      
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      
        <!-- Custom fonts for this template -->
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel='stylesheet' type='text/css'>
      
        <!-- Custom styles for this template -->
        <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

        {% block add %}{% endblock %}
      
       </head>
     


      <body>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
          <div class="container">
            {% if user.is_authenticated %}
            <a class="navbar-brand">こんにちは、{{ user.username }}さん！</a>
            {% else %}
            <a class="navbar-brand" >こんにちは、ゲストさん！</a>
            {% endif %}


            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              Menu
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'meal:top' %}">Top</a>
                </li>    
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'nutrition:nutrition' %}">Calculate</a>
                </li>                        
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'article:article_list' %}">Article</a>
                </li>

                
                  {% if user.is_authenticated %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Logout</a></li>
                  {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                  </li>
                  {% endif %}
                
              </ul>
            </div>
          </div>
        </nav>


        <!-- Page Header -->
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Record diet</h1>
            <span class="subheading">Comprehensive Diet Assistant</span>
          </div>
        </div>
      </div>
    </div>
  </header>

        {% block header %}{% endblock %}

        {% block contents %}{% endblock %}

        <!-- Footer -->
        <footer>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                  <li class="list-inline-item">
                    <a href="#">
                      <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#">
                      <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#">
                      <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Workout article 2019</p>
              </div>
            </div>
          </div>
        </footer>
      
        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      
        <!-- Custom scripts for this template -->
        <script src="{% static 'js/clean-blog.min.js' %}"></script>
      
      </body>
      





</html>

workout/article/templates/comment_create.html
{% extends 'base.html' %}
{% load static %}

{% block title%}コメントの作成{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>コメントの投稿</p>
        <p><form method="POST">
            {% csrf_token %}
            <table class="table">
               {{ form.as_table }}
           </table>
        <button type="submit" class="btn btn-primary">投稿</button>
        
        </form></p>

      </div>
    </div>
</div>

{% endblock %}