workout/meal/urls.py
from django.urls import path
from . import views

app_name = 'meal'

urlpatterns = [
    #記事関連
    path('',views.top,name="top"),
    path('meal-cal/', views.meal_cal, name="meal_cal"),
   
]

workout/meal/models.py
from django.db import models

# Create your models here.
class Meal(models.Model):
    """食品データベース"""
    food = models.CharField(max_length=100,null=False)
    energy = models.FloatField(null=False)
    protein = models.FloatField(null=False)
    fat = models.FloatField(null=False)
    carbo = models.FloatField(null=False)

workout/meal/forms.py
from django import forms


class MealFrom(forms.Form):
    amount = forms.IntegerField()
    

workout/meal/views.py
from django.shortcuts import render, redirect
from .models import Meal
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.db.models import Q
from django.contrib import messages
from pykakasi import kakasi
from .Advice import make_advice
# Create your views here.

def top(request):

    #検索条件のクエリセット取得
    query = request.GET.get('query')
    #convert Kanji to Hiragana
    ka = kakasi()
    ka.setMode('J', 'H')
    conv = ka.getConverter()
    sub_query = conv.do(str(query))
    foods = Meal.objects.all().order_by("id")[:10]    
    if (query):
        foods = Meal.objects.filter(
             Q(food__icontains=query) | Q(food__icontains=sub_query)
        )


    
    add_list = request.session.get("add", {'id': [], 'name': [], 'gram': [], 'created_num':[], 'cnt': 0})

    #削除ボタンは押されたときにセッションから削除(重複があったら最初を削除)
    delete_id = request.GET.get('delete_id')
    if(delete_id):
        for i,target in enumerate(add_list['created_num']):
            if int(delete_id) == target:
                index = i
                add_list['id'].pop(index)
                add_list['name'].pop(index)
                add_list['gram'].pop(index)
                add_list['created_num'].pop(index)

                break
    
    #すべて削除ボタンが押されたときの処理
    all_delete = request.GET.get('all_delete')
    if(all_delete):
        add_list['id'].clear()
        add_list['name'].clear()
        add_list['gram'].clear()
        add_list['created_num'].clear()
        add_list['cnt'] = 0

    #指定された食品をsessionに追加する処理(重複を許す)
    gram = request.GET.get('gram')
    food_id = request.GET.get('food_id')

    if(gram and food_id):
        meal = Meal.objects.get(pk=int(food_id))
        add_list['id'].append(int(meal.id))
        add_list['name'].append(meal.food)
        add_list['gram'].append(int(gram))
        add_list['created_num'].append(add_list['cnt'])
        add_list['cnt'] += 1
        
    request.session["add"] = add_list
    
    display = []
    for i,n,g in zip(add_list['created_num'], add_list['name'],add_list['gram']):
        display.append((i,n,g))
    
    data = {'foods':foods, 'display':display}

    return render(request,'top.html',data)

def meal_cal(request):
    add_list = request.session.get("add", {'id': [], 'name': [], 'gram': [], 'created_num': [], 'cnt': 0})
    #追加された食材の栄養素を計算
    energy, protein, fat, carbo = 0,0,0,0
    for food_id, gram in zip(add_list['id'], add_list['gram']):
        food = Meal.objects.get(pk=food_id)
        energy += food.energy * gram
        protein += food.protein * gram
        fat += food.fat * gram
        carbo += food.carbo * gram

    #計算結果のセッション情報を取得
    reduce_info = request.session.get('reduce', {})
    #アドバイスの生成
    text = ""
    if reduce_info:
        text = make_advice(reduce_info, energy, protein, fat, carbo, text)

    nutrition = {'energy':int(energy), 'protein':int(protein), 'fat':int(fat), 'carbo':int(carbo), 'reduce_info': reduce_info, 'text': text}

    return render(request, 'meal_cal.html', nutrition)

workout/meal/templates/meal_cal.html
{% extends 'base.html' %}
{% load static %}

{% block title %}トップページ{% endblock %}

{% block add %}
<link href="{% static 'css/cal.css' %}" rel="stylesheet">
<link href="{% static 'css/cal_table.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
    {% if reduce_info %}
    
    <table>
      <thead>
          <tr>
              <td class="non"></td>
              <th scope="col">摂取量</th>
              <th scope="col">目標</th>
          </tr>
      </thead>
      <tbody>
        <tr>
          <th>エネルギー</th>
          <td data-label="摂取量" class="price">{{ energy }}Kcal</td>
          <td data-label="目標値" class="price">{{ reduce_info.reduce_cal }}Kcal</td>
        </tr>        
          <tr>
              <th>タンパク質</th>
              <td data-label="摂取量" class="price">{{ protein }}g</td>
              <td data-label="目標値" class="price">{{ reduce_info.pro_g }}g</td>
          </tr>
          <tr>
              <th>炭水化物</th>
              <td data-label="摂取量" class="price">{{ carbo }}g</td>
              <td data-label="目標値" class="price">{{  reduce_info.carbo_g }}g</td>
          </tr>
          <tr>
              <th>脂質</th>
              <td data-label="摂取量" class="price">{{ fat }}g</td>
              <td data-label="目標値" class="price">{{ reduce_info.fat_g }}g</td>
          </tr>

      </tbody>
  </table>   


  <div class="box5">
    <p>{{ text | linebreaksbr }}</p>
  </div>
  
    {% else %}
    <table>
      <thead>
          <tr>
              <td class="non"></td>
              <th scope="col">摂取量</th>
              <th scope="col">目標</th>
          </tr>
      </thead>
      <tbody>
        <tr>
          <th>エネルギー</th>
          <td data-label="摂取量" class="price">{{ energy }}Kcal</td>
          <td data-label="目標値" class="price">-----</td>
        </tr>        
          <tr>
              <th>タンパク質</th>
              <td data-label="摂取量" class="price">{{ protein }}g</td>
              <td data-label="目標値" class="price">-----</td>
          </tr>
          <tr>
              <th>炭水化物</th>
              <td data-label="摂取量" class="price">{{ carbo }}g</td>
              <td data-label="目標値" class="price">-----</td>
          </tr>
          <tr>
              <th>脂質</th>
              <td data-label="摂取量" class="price">{{ fat }}g</td>
              <td data-label="目標値" class="price">-----</td>
          </tr>

      </tbody>
  </table>   



    
    <p><a class="btn-flat-logo" href="{% url 'nutrition:nutrition' %}"><i class="fa fa-chevron-right"></i>あなたに合った食事を計算！</a></p>
    <p>目標と摂取量の比較して、アドバイスを受け取ることができます</p>

    {% endif %}

</div>
</div>
</div>
{% endblock %}

workout/meal/templates/top.html
{% extends 'base.html' %}
{% load static %}

{% block title %}トップページ{% endblock %}

{% block add %}
<link href="{% static 'css/table.css' %}" rel="stylesheet">
<link href="{% static 'css/add.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h2 id="su">毎食、食べたものを追加していき食事管理ができます！</h2>
        <p class="add_f">追加された食材</p>
        {% if display %}
        <form method="GET">
        <input class="red-btn" id="all_delete" name="all_delete" type="submit" value="すべて削除">
        </form>
        {% endif %}
        <table>
         {% for s in display %}
         <tr>
        <td>{{ s.1 }}</td>
        <td>{{ s.2 }}g</td>
        <td>
          
          <form method="GET">
          <input type="hidden" name="delete_id" value="{{ s.0 }}">
          <input class="red-btn" type="submit" value="削除">
          </form>
        </td>
        </tr>
        {% endfor %}
      
    
        </table>
        {% if display %}
        <p class="calc"><a class="btn-sticky" href="{% url 'meal:meal_cal' %}">計算する</a></p>
        {% endif %}

        <form action="{% url 'meal:top' %}" method="GET">
            <input name="query" type="text" placeholder="食材名">
            <button type="submit">検索</button>
        </form>
<table>
    {% for food in foods %}
    <tr>
      <td>{{ food.food }}</td>

      <form action="{% url 'meal:top' %}" method="GET">
        <input type="hidden" name="food_id" value="{{ food.id }}">
      <td><input type="number" name="gram">g</td>
      
      <td>
        <input class="blue-btn" type="submit" value="追加">
        
      </td>
      </form>
    </tr>
    {% endfor %}

</table>

</div>
</div>
</div>
{% endblock %}